version: 3
endpoint: http://localhost:8080
metadata_directory: metadata
admin_secret: myadminsecretkey
migrations_directory: migrations
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
